apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-chatbot

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

commonLabels:
  app: todo-chatbot
  managed-by: kustomize
